/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_HX8394_A_720P_VIDEO_H_

#define _PANEL_HX8394_A_720P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/

static struct panel_config hx8394_a_720p_video_panel_data = {
  "qcom,mdss_dsi_himax8394a_720p_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 424000000, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution hx8394_a_720p_video_panel_res = {
  720, 1280, 79, 59, 60, 0, 7, 10, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info hx8394_a_720p_video_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/
static char hx8394_a_720p_video_on_cmd0[] = {
0x04, 0x00, 0x39, 0xc0,
0xB9, 0xFF, 0x83, 0x94 };


static char hx8394_a_720p_video_on_cmd1[] = {
0x11, 0x00, 0x39, 0xc0,
0xBA, 0x13, 0x82, 0x00,
0x16, 0xc5, 0x00, 0x10,
0xff, 0x0f, 0x24, 0x03,
0x21, 0x24, 0x25, 0x20,
0x08, 0xff, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd2[] = {
0x10, 0x00, 0x39, 0xc0,
0xB1, 0x01, 0x00, 0x37,
0x8a, 0x01, 0x12, 0x12,
0x2C, 0x34, 0x2b, 0x2b,
0x57, 0x02, 0x00, 0xE6 };


static char hx8394_a_720p_video_on_cmd3[] = {
0x03, 0x00, 0x39, 0xc0,
0xBF, 0x06, 0x02, 0xff};


static char hx8394_a_720p_video_on_cmd4[] = {
0x07, 0x00, 0x39, 0xc0,
0xB2, 0x00, 0xC8, 0x0E,
0x30, 0x00, 0x22, 0xff };


static char hx8394_a_720p_video_on_cmd5[] = {
0x05, 0x00, 0x39, 0xc0,
0xB0, 0x01, 0x0A, 0x39,
0x80, 0xff, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd6[] = {
0x20, 0x00, 0x39, 0xc0,
0xB4, 0x80, 0x08, 0x32,
0x10, 0x06, 0x32, 0x10,
0x01, 0x22, 0x10, 0x08,
0x38, 0x07, 0x52, 0x0c,
0x37, 0x00, 0x5F, 0x0A,
0x6F, 0x6F, 0x0A, 0x06,
0x44, 0x06, 0x5F, 0x0A,
0x6B, 0x70, 0x05, 0x08 };


static char hx8394_a_720p_video_on_cmd7[] = {
0x3f, 0x00, 0x39, 0xc0,
0xD5, 0x00, 0x00, 0x00,
0x00, 0x0A, 0x00, 0x01,
0x22, 0x00, 0x00, 0x33,
0x00, 0x23, 0x01, 0x67,
0x45, 0x01, 0x23, 0x88,
0x88, 0x88, 0x88, 0x88,
0x88, 0x88, 0x88, 0x88,
0x88, 0x88, 0x45, 0x99,
0x88, 0x54, 0x76, 0x10,
0x32, 0x32, 0x10, 0x88,
0x88, 0x88, 0x88, 0x88,
0x88, 0x88, 0x88, 0x88,
0x88, 0x88, 0x54, 0x99,
0x88, 0x3C, 0x0A, 0x00,
0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0xff};


static char hx8394_a_720p_video_on_cmd8[] = {
0x02, 0x00, 0x39, 0xc0,
0xB6, 0x15, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd9[] = {
0x02, 0x00, 0x39, 0xc0,
0xC6, 0x08, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd10[] = {
0x02, 0x00, 0x39, 0xc0,
0xBC, 0x07, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd11[] = {
0x2c, 0x00, 0x39, 0xc0,
0xE0, 0x00, 0x1a, 0x22,
0x2f, 0x2d, 0x3f, 0x32,
0x32, 0x4b, 0x09, 0x10,
0x10, 0x13, 0x16, 0x14,
0x15, 0x11, 0x18, 0x00,
0x1a, 0x22, 0x2F, 0x2D,
0x3f, 0x32, 0x4b, 0x09,
0x10, 0x10, 0x13, 0x16,
0x14, 0x15, 0x11, 0x18,
0x0d, 0x18, 0x08, 0x10,
0x0d, 0x18, 0x08, 0x10 };


static char hx8394_a_720p_video_on_cmd12[] = {
0x02, 0x00, 0x39, 0xc0,
0xCC, 0x09, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd13[] = {
0x02, 0x00, 0x39, 0xc0,
0x3A, 0x70, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd14[] = {
0x05, 0x00, 0x39, 0xc0,
0xC7, 0x00, 0x10, 0x00,
0x10, 0xff, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd15[] = {
0x03, 0x00, 0x39, 0xc0,
0xBF, 0x06, 0x02, 0xff };


static char hx8394_a_720p_video_on_cmd16[] = {
0x11, 0x00, 0x05, 0x80 };


static char hx8394_a_720p_video_on_cmd17[] = {
0x29, 0x00, 0x05, 0x80 };


static char hx8394_a_720p_video_on_cmd18[] = {
0x02, 0x00, 0x39, 0xc0,
0x51, 0xff, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd19[] = {
0x02, 0x00, 0x39, 0xc0,
0x53, 0x24, 0xff, 0xff };


static char hx8394_a_720p_video_on_cmd20[] = {
0x02, 0x00, 0x39, 0xc0,
0x55, 0x01, 0xff, 0xff };


static struct mipi_dsi_cmd hx8394_a_720p_video_on_command[] = {
{ 0x8 , hx8394_a_720p_video_on_cmd0},
{ 0x18 , hx8394_a_720p_video_on_cmd1},
{ 0x14 , hx8394_a_720p_video_on_cmd2},
{ 0x8 , hx8394_a_720p_video_on_cmd3},
{ 0xc , hx8394_a_720p_video_on_cmd4},
{ 0xc , hx8394_a_720p_video_on_cmd5},
{ 0x24 , hx8394_a_720p_video_on_cmd6},
{ 0x44 , hx8394_a_720p_video_on_cmd7},
{ 0x8 , hx8394_a_720p_video_on_cmd8},
{ 0x8 , hx8394_a_720p_video_on_cmd9},
{ 0x8 , hx8394_a_720p_video_on_cmd10},
{ 0x30 , hx8394_a_720p_video_on_cmd11},
{ 0x8 , hx8394_a_720p_video_on_cmd12},
{ 0x8 , hx8394_a_720p_video_on_cmd13},
{ 0xc , hx8394_a_720p_video_on_cmd14},
{ 0x8 , hx8394_a_720p_video_on_cmd15},
{ 0x4 , hx8394_a_720p_video_on_cmd16},
{ 0x4 , hx8394_a_720p_video_on_cmd17},
{ 0x8 , hx8394_a_720p_video_on_cmd18},
{ 0x8 , hx8394_a_720p_video_on_cmd19},
{ 0x8 , hx8394_a_720p_video_on_cmd20},
};
#define HX8394_A_720P_VIDEO_ON_COMMAND 21


static char hx8394_a_720p_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char hx8394_a_720p_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd hx8394_a_720p_video_off_command[] = {
{ 0x4 , hx8394_a_720p_videooff_cmd0},
{ 0x4 , hx8394_a_720p_videooff_cmd1}
};
#define HX8394_A_720P_VIDEO_OFF_COMMAND 2


static struct command_state hx8394_a_720p_video_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info hx8394_a_720p_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info hx8394_a_720p_video_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration hx8394_a_720p_video_lane_config = {
  4, 0, 1, 1, 1, 1
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
const uint32_t hx8394_a_720p_video_timings[] = {
  0x8d, 0x24, 0x19, 0x00, 0x34, 0x34, 0x1d, 0x26, 0x2a, 0x03, 0x04, 0x00
};

static struct panel_timing hx8394_a_720p_video_timing_info = {
  0, 4, 0x1e, 0x38
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight hx8394_a_720p_video_backlight = {
  1, 1, 255, 100, 1, "PMIC_8941"
};


#endif /*_PANEL_HX8394_A_720P_VIDEO_H_*/
