/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_ILI9488_HVGA_VIDEO_H_

#define _PANEL_ILI9488_HVGA_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/

static struct panel_config ili9488_hvga_video_panel_data = {
  "qcom,mdss_dsi_ili9488_hvga_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 424000000, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution ili9488_hvga_video_panel_res = {
  320, 480, 160, 20, 10, 0, 80, 16, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info ili9488_hvga_video_color = {
  24, 0, 0xff, 0, 0, 0
};
	
/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/
static char reg0xE0[20] = {
0x10, 0x00, 0x29, 0xC0,
0xE0, 0x00, 0x07, 0x0A,
0x06, 0x11, 0x07, 0x26,
0xBD, 0x3C, 0x09, 0x17,
0x0A, 0x26, 0x22, 0x0F
};

static char reg0xE1[20] = {
0x10, 0x00, 0x29, 0xC0,
0xE1, 0x00, 0x22, 0x31,
0x0C, 0x1C, 0x0C, 0x4C,
0x76, 0x62, 0x0B, 0x16,
0x0F, 0x39, 0x39, 0x0F
};

static char reg0xC0[8] = {
0x03, 0x00, 0x29, 0xC0,
0xC0, 0x10, 0x0A, 0xFF,
};

static char reg0xC1[8] = {//inner scan 70hz
0x02, 0x00, 0x29, 0xC0,
0xC1, 0x45, 0xFF, 0xFF
};

static char reg0xC5[8] = {
0x04, 0x00, 0x29, 0xC0,
0xC5, 0x00, 0x27, 0x80
};

static char reg0x36[8] = {
0x02, 0x00, 0x29, 0xC0,
0x36, 0x08, 0xFF, 0xFF
};

static char reg0x3A[8] = {
0x02, 0x00, 0x29, 0xC0,
0x3A, 0x66, 0xFF, 0xFF
};

static char reg0x21[4] = {
0x21, 0x00, 0x05, 0x80
};

static char reg0xB0[8] = {
0x02, 0x00, 0x29, 0xC0,
0xB0, 0x00, 0xFF, 0xFF
};

static char reg0xB1[8]= {
0x02, 0x00, 0x29, 0xC0,
0xB1, 0xA0, 0xFF, 0xFF
};

static char reg0xB4[8]= {
0x02, 0x00, 0x29, 0xC0,
0xB4, 0x02, 0xFF, 0xFF
};

static char reg0xB6[8]= {
0x03, 0x00, 0x29, 0xC0,
0xB6, 0x02, 0x22, 0xFF
};

static char reg0xE9[8]= {
0x02, 0x00, 0x29, 0xC0,
0xE9, 0x00, 0xFF, 0xFF
};

static char reg0xF7[12]= {
0x05, 0x00, 0x29, 0xC0,
0xF7, 0xA9, 0x51, 0x2C,
0x82, 0xFF, 0xFF, 0xFF
};

static char reg0xF8[8]= {
0x03, 0x00, 0x29, 0xC0,
0xF8, 0x21, 0x05, 0xFF,
};

static char reg0x11[4] = {0x11, 0x00, 0x05, 0x80};

static char reg0x29[4] ={0x29, 0x00, 0x05, 0x80};

static struct mipi_dsi_cmd ili9488_hvga_video_on_command[] = {
{0x14, reg0xE0},
{0x14, reg0xE1},
{0x08, reg0xC0},
{0x08, reg0xC1},
{0x08, reg0xC5},
{0x08, reg0x36},
{0x08, reg0x3A},
{0x04, reg0x21},
{0x08, reg0xB0},
{0x08, reg0xB1},
{0x08, reg0xB4},
{0x08, reg0xB6},
{0x08, reg0xE9},
{0x0C, reg0xF7},
//{0x08, reg0xF8},
{0x04, reg0x11},
{0x04, reg0x29},//100ms
};
#define ILI9488_HVGA_VIDEO_ON_COMMAND 16


static char ili9488_hvga_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char ili9488_hvga_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };


static struct mipi_dsi_cmd ili9488_hvga_video_off_command[] = {
{ 0x4 , ili9488_hvga_videooff_cmd0},
{ 0x4 , ili9488_hvga_videooff_cmd1}
};
#define ILI9488_HVGA_VIDEO_OFF_COMMAND 2


static struct command_state ili9488_hvga_video_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info ili9488_hvga_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info ili9488_hvga_video_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x8
  /*1, 1, 1, 1, 1, 1, 2, 1, 0x8*/
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration ili9488_hvga_video_lane_config = {
  1, 0, 1, 0, 0, 0
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
const uint32_t ili9488_hvga_video_timings[] = {
0x50, 0x12, 0x0C, 0x00, 0x33, 0x38, 0x10, 0x16, 0x1E, 0x03, 0x04, 0x00
  //0x46, 0x1d, 0x20, 0x00, 0x39, 0x3a, 0x21, 0x21, 0x32, 0x03, 0x04, 0x00
  //0x7d, 0x25, 0x1d, 0x00, 0x37, 0x33, 0x22, 0x27, 0x1e, 0x03, 0x04, 0x00
};


static struct mipi_dsi_cmd ili9488_hvga_video_rotation[] = {

};
#define ILI9488_HVGA_VIDEO_ROTATION 0


static struct panel_timing ili9488_hvga_video_timing_info = {
  0, 4, 0x70, 0x42
};

static struct panel_reset_sequence ili9488_hvga_video_panel_reset_seq = {
{ 1, 0, 1, }, { 20, 20, 20, }, 2
};
/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight ili9488_hvga_video_backlight = {
  1, 1, 4095, 100, 1, "PMIC_8941"
};


#endif /*_PANEL_ILI9488_HVGA_VIDEO_H_*/


